import type { Metadata } from "next";
import { Inter } from "@next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Navigation from "./components/Navigation";
import Container from "./components/Container";

const inter = Inter({ subsets: ["latin"], weight: '400' });

const SITE_TITLE = "Portfólio 2024";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header siteTitle={SITE_TITLE}>
          <Navigation />
        </Header>
        <main className="min-h-screen">
          <Container className="mt-11">
            {children}
          </Container>
        </main>
        <Footer siteTitle={SITE_TITLE} />
      </body>
    </html>
  );
}
